#!/bin/bash

if [ ! "$1" == "upgrade" ]; then
    echo "[*] AutoEntitle: Removing..."
    mv /var/AUTOENTREALDPKG /usr/bin/dpkg
    rm /usr/bin/dpkz
    rm /var/*AUTOENT*
    rm /tmp/*AUTOENT*
else
    echo "[*] AutoEntitle: Upgrading..."
    mv /var/AUTOENTDPKG /usr/bin/dpkg
fi
echo "[*] AutoEntitle: Done :)"